---
:ems:
  :ems_redfish:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :general:
          :critical:
          - !ruby/regexp /^redfish_/
:http_proxy:
  :redfish:
    :host:
    :password:
    :port:
    :user:
:workers:
  :ems_refresh_worker_redfish_physical_infra:
    :inherits_from: ems_refresh_worker
  :event_catcher_redfish:
    :inherits_from: event_catcher
